apiVersion: apps/v1
kind: Deployment
metadata:
  name: gasrapido-web
  labels:
    app: gasrapido-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gasrapido-web
  template:
    metadata:
      labels:
        app: gasrapido-web
    spec:
      containers:
      - name: web
        image: gasrapido/web:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: NEXT_PUBLIC_SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: supabase-url
        - name: NEXT_PUBLIC_SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: supabase-anon-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: gasrapido-web-service
spec:
  selector:
    app: gasrapido-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gasrapido-mobile
  labels:
    app: gasrapido-mobile
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gasrapido-mobile
  template:
    metadata:
      labels:
        app: gasrapido-mobile
    spec:
      containers:
      - name: mobile
        image: gasrapido/mobile:latest
        ports:
        - containerPort: 19006
        env:
        - name: NODE_ENV
          value: "production"
        - name: EXPO_PUBLIC_SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: supabase-url
        - name: EXPO_PUBLIC_SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: supabase-anon-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: gasrapido-mobile-service
spec:
  selector:
    app: gasrapido-mobile
  ports:
    - protocol: TCP
      port: 80
      targetPort: 19006
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-db
  labels:
    app: supabase-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supabase-db
  template:
    metadata:
      labels:
        app: supabase-db
    spec:
      containers:
      - name: postgres
        image: supabase/postgres:15.1.0.147
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: db-password
        - name: POSTGRES_DB
          value: "postgres"
        volumeMounts:
        - name: supabase-data
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
      volumes:
      - name: supabase-data
        persistentVolumeClaim:
          claimName: supabase-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: supabase-db-service
spec:
  selector:
    app: supabase-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-auth
  labels:
    app: supabase-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supabase-auth
  template:
    metadata:
      labels:
        app: supabase-auth
    spec:
      containers:
      - name: gotrue
        image: supabase/gotrue:v2.69.1
        ports:
        - containerPort: 9999
        env:
        - name: GOTRUE_DB_DRIVER
          value: "postgres"
        - name: GOTRUE_DB_DATABASE_URL
          value: "postgres://postgres:$(DB_PASSWORD)@supabase-db-service:5432/postgres"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: db-password
        - name: GOTRUE_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: jwt-secret
        - name: GOTRUE_JWT_EXP
          value: "3600"
        - name: GOTRUE_EXTERNAL_EMAIL_ENABLED
          value: "true"
        - name: GOTRUE_EXTERNAL_PHONE_ENABLED
          value: "true"
        - name: GOTRUE_MAILER_AUTOCONFIRM
          value: "true"
        - name: GOTRUE_SMS_AUTOCONFIRM
          value: "true"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: supabase-auth-service
spec:
  selector:
    app: supabase-auth
  ports:
    - protocol: TCP
      port: 9999
      targetPort: 9999
  type: ClusterIP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: supabase-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi