# Default values for gasrapido.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Global values
global:
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: ""

# Web application configuration
web:
  name: gasrapido-web
  replicaCount: 3
  image:
    repository: gasrapido/web
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  service:
    type: LoadBalancer
    port: 80
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
  nodeSelector: {}
  tolerations: []
  affinity: {}

# Mobile application configuration
mobile:
  name: gasrapido-mobile
  replicaCount: 2
  image:
    repository: gasrapido/mobile
    pullPolicy: IfNotPresent
    tag: ""
  service:
    type: LoadBalancer
    port: 80
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

# Supabase configuration
supabase:
  db:
    name: supabase-db
    replicaCount: 1
    image:
      repository: supabase/postgres
      tag: 15.1.0.147
    service:
      type: ClusterIP
      port: 5432
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi
    persistence:
      enabled: true
      size: 10Gi
      accessModes:
        - ReadWriteOnce
  auth:
    name: supabase-auth
    replicaCount: 1
    image:
      repository: supabase/gotrue
      tag: v2.69.1
    service:
      type: ClusterIP
      port: 9999
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi

# Ingress configuration
ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: gasrapido.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# Secrets configuration
secrets:
  enabled: true
  supabaseUrl: ""
  supabaseAnonKey: ""
  supabaseServiceRoleKey: ""
  dbPassword: ""
  jwtSecret: ""

# Monitoring configuration
monitoring:
  enabled: true
  prometheus:
    enabled: true
  grafana:
    enabled: true